### ISSUE TITLE
smart upgrade feature 

### ISSUE THREAD

**Issue by jbauernberger** [streembit/streembitui#10]
was just thinking about how to notify users in case of critical security updates. We could define a branching strategy where the startup script checks if there is a newer revision of the current revision on an emergency branch. if it exists the app does not come up but informs the user that he must upgrade if he wishes to run streembit. this could help push new updates quickly and avoid having stale versions around that have extremely critical security vulnerabilities.

**Comment by zsoltpardi** [comment]
Thanks for suggesting this feature. We will implement this in the next release.
