### ISSUE TITLE
File transfer reliability 

### ISSUE THREAD

**Issue by HelloChrome** [streembit/streembitui#196]
Within the Streembit UI there is facility to securely send a file between contacts.  The current problem exists when a user attempts to send a file within the chat feature of the application.   The file transfer appears to freeze periodically for the receiving party on some file transfers.  Also review of the file size limits need to be reviewed and evaluated.  This information would be useful as a notice to users when sending files. 

The logic of this fix also needs to be in place for the file transfer operation outside of the chat function, which is possible from the actions menu when the contact tile is opened.... see screenshot attached 
![screen shot 2018-07-09 at 21 49 13](https://user-images.githubusercontent.com/34679523/42475249-fcb6cf3e-83c1-11e8-8722-9b2d0865100a.png)

**Comment by HelloChrome** [comment]
A further bug manifests when attempting to send files from a mobile device where the file in the transfer is corrupted or not completely processed in the example of an image.  Also files sent from a mobile device is sent multiple times most often as a duplicate x2 files.  Correct operation should be one file transferred completely.

**Comment by alexDou** [comment]
commit #23107f0 has a possible solution. I don't want to mark it solved till file transfer thoroughly tested across platforms
