### ISSUE TITLE
Duplication of messages in 'Notification' dialogue

### ISSUE THREAD

**Issue by HelloChrome** [streembit/streembitui#204]
Currently when the UI is opened by the user there are a number of status messages generated in the notification dialogue box.   The user can click on the notification icon in the top bar to read the messages in a small dialogue box which opens.   Currently these status messages duplicate creating an excessive number of messages, mostly created by the status of the other contacts who may or may not be online.  Correct operation should be to only create a status once and then again if the contact then comes online.

**Comment by alexDou** [comment]
commit #77ac7f2 solves error messages duplication
