### ISSUE TITLE
Fit the text chat in audio call view

### ISSUE THREAD

**Issue by zsoltpardi** [streembit/streembitui#48]
On smaller screen resolution devices such as a laptop the during the audio call the user opens text chat and the text chat window and send button don't fit into the screen and a vertical scrollbar is initialized. Try to fit the text chat controls into the screen without showing a vertical scrollbar when the vertical screen resolution is equal or bigger than 768px. Show the vertical scrollbar when the screen resolution is smaller.
We can make the audio signal visualization smaller at the top of the audio call view to have more space for the text chat controls.

**Comment by zsoltpardi** [comment]
I am reopening this as on a not high end but fairly average laptop the chat still doesn't fit into the screen without having a vertical scroll bar. The vertical resolution is 768 px of this device. Such average device should be able to use the chat without a vertical scrollbar. We should put scroll bar on the messages but the contact text chat and the send button should be within the screen and then for mobile devices we will have another screen arrangement via media queries.

**Comment by alexDou** [comment]
It's done. 
I don't want to close the issue because there is no such resolution in my system and I just mimicked it. need a test on native 768px height

**Comment by HelloChrome** [comment]
I'll test it shortly and report back

**Comment by zsoltpardi** [comment]
I don't think we are doing the right thing in regards to this. The intention with the audio signal visualization was to show something on the screen during an audio call, as well as to show the audio control. I thought having an empty screen looks a bit odd and then I was showing that audio signals. But since that audio signal display has very little value other than cosmetics, when there is a text chat is going on we should minimize that audio signal display. Currently half of the screen is occupied by the audio signal + audio control which makes no sense. When the text chat is operational the audio controls are still important, but the audio signal should take as little space as it is possible.

**Comment by alexDou** [comment]
can we close it?
