### ISSUE TITLE
The WebRTC dependencies are not  the latest.

### ISSUE THREAD

**Issue by zsoltpardi** [streembit/streembitui#49]
We need to update WebRTC dependencies to the latest, especially the adapter https://github.com/webrtc/adapter. Also, try to follow the approach of the WebRTC samples at https://github.com/webrtc/samples so use those dependencies which the WebRTC samples project uses.  Like the samples project uses this https://www.npmjs.com/package/eslint-config-webrtc we should try to have the same approach.

**Comment by alexDou** [comment]
webrtc-adapter was updated to the latest. dependencies was updated to the latest also including pulling a new package. does it close the issue?
