### ISSUE TITLE
Seed list is not flexible

### ISSUE THREAD

**Issue by zsoltpardi** [streembit/streembitui#50]
Currently the seed list is coming from the lib/config.js file. We need to keep this as a last resort to get the seeds but we need a more flexible and configurable way to get the seeds. One option is to get the seed from a Github repository, so create a new repository like streembit-seeds, have a json file  and list the seeds  array there, so users always have the latest valid seeds list upon application initialization.

**Comment by tanvirrb** [comment]
Create the repo. I'll working on it. Assign the task to me.

**Comment by zsoltpardi** [comment]
This issue cannot be closed until the changes were not reviewed.

**Comment by zsoltpardi** [comment]
This commit at https://github.com/streembit/streembitui/commit/06b2c36bf576e9ddde90803fe987baa681d71e32 fixes this issue.
