### ISSUE TITLE
Open text chat during audio and video call

### ISSUE THREAD

**Issue by zsoltpardi** [streembit/streembitui#74]
When there is an audio and video call and the contact sends a text message the app should open and display the text chat controls automatically.

**Comment by l-shirinyan** [comment]
During the audio call receiving the message, I got this scenario: https://prnt.sc/i5g0j6.
Clicking on envelope icon opens the text chat https://prnt.sc/i5g1wk.
Here is my question:
Receiving the message text chat should open and stop audio or video call automatically?

**Comment by zsoltpardi** [comment]
Partly that's why we need to remove the envelope (when the contact is the selected contact), because that is incorrect if during a video/audio call the user receives a message and then the call is terminated. The call should remain operational and the text chat should be shown in the call window.
