### ISSUE TITLE
Contacts Bar view

### ISSUE THREAD

**Issue by HelloChrome** [streembit/streembitui#76]
The Contacts list is too short in height.  Once a contact list is beyond x4 contacts the user has to scroll through. 

Better to have the contact bar height to extend to the bottom of the screen.  This way at least x10 contacts should be shown without needing to scroll through them.

**Comment by zsoltpardi** [comment]
As the opening post of this issue describes the contact bar should be 100% height. Currently the contact bar is not 100% height.
